### ISSUE TITLE
Languagetool don't ignore files ending in .git (and other virtual files)

### ISSUE THREAD

**Issue by faustinoaq** [adamvoss/vscode-languagetool#2]
Hi @adamvoss , great extension!

I have a issue with `.git` directories, my problems look like:

![screenshot_20170613_230734](https://user-images.githubusercontent.com/3067335/27115003-526f48a2-508d-11e7-8e9b-b8040f82eefd.png)

As suggestion you could ignore all these dirs:

```json
  "files.exclude": {
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/.git": true,
    "**/.hg": true,
    "**/.svn": true,
    "**/.shards": true,
    "**/lib": true,
    "**/node_modules": true
  },
```

The above dirs are under `files.exclude` inside `settings.json`

**Comment by adamvoss** [comment]
Thanks @faustinoaq!

I had no idea this could do "full project" checking like that.  (I'd never used the Problems panel :smile:)

Did adding the exclusion you gave work for you?  It didn't seem to work for me, but I notice that these are not files in the `.git` directory.  Rather they are files ending in .git, served under a "git:/" protocol (rather than actual files).  I'll see what I can do about this tomorrow.

**Comment by faustinoaq** [comment]
> Did adding the exclusion you gave work for you?

It didn't work for me :sweat_smile:

Yes, languagetool is checking files inside `git:/` protocol, Projects without git repository work without duplicate problems:

![screenshot_20170614_053427](https://user-images.githubusercontent.com/3067335/27128336-aefc4e04-50c3-11e7-9ce1-f9b76a4ed892.png)

Maybe if this extension check only files, avoiding other protocols like: `git:/`, `memory:/`, `svn:/` etc and allowing to exclude large directories, like `node_modules` or `.git`.

**Comment by adamvoss** [comment]
@faustinoaq Thanks for your help! `0.0.3` is now live on the marketplace and should fix this.  Let me know if you still have issues.
